import { Job, ResumeProfile, Interview, Activity, Goal, Settings } from '../types';
import { DEFAULT_FOLLOW_UP_TEMPLATES } from './defaultTemplates';

export function generateDemoData(): {
  jobs: Job[];
  resumes: ResumeProfile[];
  interviews: Interview[];
  activities: Activity[];
  goals: Goal[];
  settings: Settings;
} {
  const now = new Date();
  const formatDaysAgo = (days: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() - days);
    return d.toISOString().split('T')[0];
  };

  const formatDaysFuture = (days: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0];
  };

  const resumes: ResumeProfile[] = [
    {
      id: 'res-sde-v3',
      name: 'SDE_Resume_v3',
      targetRole: 'Senior Software Engineer / Backend Lead',
      skills: ['TypeScript', 'React', 'Node.js', 'Go', 'PostgreSQL', 'Docker', 'AWS', 'System Design', 'GraphQL', 'Redis'],
      version: '3.2',
      notes: 'Tailored for distributed systems, backend APIs, and full-stack cloud roles.',
      isDefault: true,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'res-qa-lead',
      name: 'QA_Lead_Resume_v2',
      targetRole: 'QA Automation Engineer / SDET Lead',
      skills: ['Playwright', 'Selenium', 'Cypress', 'Java', 'Python', 'CI/CD Pipelines', 'API Testing', 'Jest', 'Postman', 'TestRail'],
      version: '2.1',
      notes: 'Optimized for test architecture, end-to-end automation, and quality strategy.',
      isDefault: false,
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'res-frontend-v1',
      name: 'Frontend_Staff_Resume',
      targetRole: 'Staff Frontend Engineer / UI Architect',
      skills: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript', 'Web Performance', 'Micro-frontends', 'State Management', 'Figma', 'Accessibility (a11y)'],
      version: '1.4',
      notes: 'Design-system heavy resume showcasing performance, animation, and enterprise SPAs.',
      isDefault: false,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
  ];

  const jobs: Job[] = [
    {
      id: 'job-google-1',
      companyName: 'Google',
      jobTitle: 'Senior Software Engineer, Cloud Core',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/google-cloud-sde',
      resumeId: 'res-sde-v3',
      dateApplied: formatDaysAgo(4),
      salaryRange: '$195,000 - $240,000 + Equity',
      notes: 'Referral from Alex in Cloud Infrastructure. Team handles high-throughput control plane.',
      status: 'interview',
      location: 'Sunnyvale, CA (Hybrid)',
      employmentType: 'full-time',
      workMode: 'hybrid',
      recruiterName: 'Sarah Jenkins',
      recruiterEmail: 'sjenkins@google.example.com',
      referralName: 'Alex Mercer (Staff SWE)',
      interviewDate: formatDaysFuture(2),
      nextFollowUpDate: formatDaysFuture(3),
      order: 0,
      priority: 'high',
      tags: ['Tier 1', 'Cloud', 'Distributed Systems'],
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'job-microsoft-1',
      companyName: 'Microsoft',
      jobTitle: 'Principal SDET / Test Lead (Azure)',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/microsoft-azure-sdet',
      resumeId: 'res-qa-lead',
      dateApplied: formatDaysAgo(12),
      salaryRange: '$180,000 - $220,000',
      notes: 'Completed 2 technical rounds on distributed system testing. Final loop scheduled.',
      status: 'interview',
      location: 'Redmond, WA (Remote friendly)',
      employmentType: 'full-time',
      workMode: 'remote',
      recruiterName: 'Marcus Vance',
      recruiterEmail: 'm.vance@microsoft.example.com',
      interviewDate: formatDaysFuture(5),
      nextFollowUpDate: formatDaysFuture(6),
      order: 1,
      priority: 'high',
      tags: ['Azure', 'Automation', 'Remote'],
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'job-amazon-1',
      companyName: 'Amazon',
      jobTitle: 'Software Development Engineer II',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/amazon-sde2',
      resumeId: 'res-sde-v3',
      dateApplied: formatDaysAgo(9),
      salaryRange: '$165,000 - $205,000',
      notes: 'Applied through careers portal. Need to follow up with recruiter on status.',
      status: 'applied',
      location: 'Seattle, WA',
      employmentType: 'full-time',
      workMode: 'hybrid',
      recruiterName: 'Elena Rostova',
      recruiterEmail: 'elena.r@amazon.example.com',
      nextFollowUpDate: formatDaysAgo(1),
      order: 0,
      priority: 'medium',
      tags: ['AWS', 'E-Commerce'],
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      id: 'job-adobe-1',
      companyName: 'Adobe',
      jobTitle: 'Senior Frontend Architect',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/adobe-creative-cloud-fe',
      resumeId: 'res-frontend-v1',
      dateApplied: formatDaysAgo(6),
      salaryRange: '$185,000 - $215,000',
      notes: 'Followed up after submitting application with hiring manager on LinkedIn.',
      status: 'follow-up',
      location: 'San Jose, CA',
      employmentType: 'full-time',
      workMode: 'remote',
      recruiterName: 'David Cho',
      recruiterEmail: 'dcho@adobe.example.com',
      nextFollowUpDate: formatDaysFuture(1),
      order: 0,
      priority: 'high',
      tags: ['Creative Cloud', 'Canvas', 'WebGL'],
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'job-stripe-1',
      companyName: 'Stripe',
      jobTitle: 'Staff Backend Infrastructure Engineer',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/stripe-staff-swe',
      resumeId: 'res-sde-v3',
      dateApplied: formatDaysAgo(20),
      salaryRange: '$225,000 - $275,000 + Equity',
      notes: 'Offer received! Reviewing package details and team placement.',
      status: 'offer',
      location: 'San Francisco, CA (Remote)',
      employmentType: 'full-time',
      workMode: 'remote',
      recruiterName: 'Jessica Taylor',
      recruiterEmail: 'jtaylor@stripe.example.com',
      order: 0,
      priority: 'high',
      tags: ['Fintech', 'Offer', 'Payments'],
      createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'job-atlassian-1',
      companyName: 'Atlassian',
      jobTitle: 'Senior Fullstack Engineer, Jira Systems',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/atlassian-jira-fullstack',
      resumeId: 'res-sde-v3',
      dateApplied: formatDaysAgo(2),
      salaryRange: '$175,000 - $210,000',
      notes: 'Applied on company career site. Recruiter screening call tentatively proposed.',
      status: 'applied',
      location: 'Remote, US',
      employmentType: 'full-time',
      workMode: 'remote',
      recruiterName: 'Kavita Patel',
      recruiterEmail: 'kpatel@atlassian.example.com',
      order: 1,
      priority: 'medium',
      tags: ['Productivity', 'React', 'Java'],
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'job-databricks-1',
      companyName: 'Databricks',
      jobTitle: 'Platform Automation Engineer',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/databricks-automation',
      resumeId: 'res-qa-lead',
      salaryRange: '$190,000 - $230,000',
      notes: 'Opportunity found on HackerNews Who is Hiring thread. Need to polish cover note.',
      status: 'wishlist',
      location: 'San Francisco, CA',
      employmentType: 'full-time',
      workMode: 'hybrid',
      order: 0,
      priority: 'medium',
      tags: ['Big Data', 'Spark', 'Infrastructure'],
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'job-figma-1',
      companyName: 'Figma',
      jobTitle: 'Design Systems & UI Engineer',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/figma-ui-swe',
      resumeId: 'res-frontend-v1',
      salaryRange: '$190,000 - $235,000',
      notes: 'Preparing custom portfolio links demonstrating component library benchmarks.',
      status: 'wishlist',
      location: 'New York, NY (Hybrid)',
      employmentType: 'full-time',
      workMode: 'hybrid',
      order: 1,
      priority: 'high',
      tags: ['Design Systems', 'Wasm', 'TypeScript'],
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'job-uber-1',
      companyName: 'Uber',
      jobTitle: 'Software Engineer, Driver Experience',
      linkedinUrl: 'https://www.linkedin.com/jobs/view/uber-swe',
      resumeId: 'res-sde-v3',
      dateApplied: formatDaysAgo(25),
      salaryRange: '$170,000 - $210,000',
      notes: 'Position filled internally after initial screening.',
      status: 'rejected',
      location: 'San Francisco, CA',
      employmentType: 'full-time',
      workMode: 'hybrid',
      order: 0,
      priority: 'low',
      tags: ['Mobility', 'Real-time'],
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
  ];

  const interviews: Interview[] = [
    {
      id: 'int-google-1',
      jobId: 'job-google-1',
      companyName: 'Google',
      jobTitle: 'Senior Software Engineer, Cloud Core',
      date: formatDaysFuture(2),
      time: '14:00',
      round: 'Technical Round 2: Distributed Systems & Concurrency',
      interviewer: 'David Lin (Principal Engineer)',
      meetingUrl: 'https://meet.google.com/abc-hireflow-demo',
      format: 'video',
      notes: 'Focus on Raft consensus, sharding strategies, and zero-downtime database migrations.',
      result: 'scheduled',
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'int-microsoft-1',
      jobId: 'job-microsoft-1',
      companyName: 'Microsoft',
      jobTitle: 'Principal SDET / Test Lead (Azure)',
      date: formatDaysFuture(5),
      time: '10:30',
      round: 'Hiring Manager & System Architecture',
      interviewer: 'Rachel Chang (Director of Engineering)',
      meetingUrl: 'https://teams.microsoft.com/l/meetup-join/hireflow-demo',
      format: 'video',
      notes: 'Prepare leadership philosophy examples, failure recovery mechanisms in Azure, and test frameworks.',
      result: 'scheduled',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'int-stripe-past',
      jobId: 'job-stripe-1',
      companyName: 'Stripe',
      jobTitle: 'Staff Backend Infrastructure Engineer',
      date: formatDaysAgo(7),
      time: '13:00',
      round: 'Final Executive Loop & Team Match',
      interviewer: 'Patrick K. & Infrastructure Staff',
      meetingUrl: 'https://meet.google.com/xyz-stripe-demo',
      format: 'video',
      notes: 'Very strong alignment on latency optimization and fault-tolerant event processing. Resulted in offer!',
      result: 'passed',
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
  ];

  const activities: Activity[] = [
    {
      id: 'act-1',
      jobId: 'job-stripe-1',
      type: 'status_changed',
      description: 'Received official Offer from Stripe for Staff Backend Infrastructure Engineer ($225k+)',
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'act-2',
      jobId: 'job-google-1',
      type: 'interview_added',
      description: 'Scheduled Technical Round 2 with Google Cloud Core for 2 days from now',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'act-3',
      jobId: 'job-adobe-1',
      type: 'followup_sent',
      description: 'Sent customized LinkedIn follow-up note to David Cho at Adobe',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'act-4',
      jobId: 'job-atlassian-1',
      type: 'job_created',
      description: 'Applied to Atlassian — Senior Fullstack Engineer using SDE_Resume_v3',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'act-5',
      jobId: 'job-microsoft-1',
      type: 'status_changed',
      description: 'Advanced Microsoft application to Interview round (Azure Test Lead)',
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'act-6',
      jobId: 'job-amazon-1',
      type: 'job_created',
      description: 'Applied to Amazon — Software Development Engineer II',
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      id: 'act-7',
      type: 'resume_updated',
      description: 'Updated SDE_Resume_v3 with recent Cloud performance metrics and Go benchmarks',
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
  ];

  const goals: Goal[] = [
    {
      id: 'goal-weekly-apps',
      type: 'applications',
      title: 'Submit high-signal applications',
      target: 8,
      period: 'weekly',
      startDate: formatDaysAgo(4),
      endDate: formatDaysFuture(3),
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'goal-interviews',
      type: 'interviews',
      title: 'Complete interview rounds',
      target: 3,
      period: 'weekly',
      startDate: formatDaysAgo(4),
      endDate: formatDaysFuture(3),
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'goal-followups',
      type: 'followups',
      title: 'Recruiter follow-ups & warm pings',
      target: 5,
      period: 'weekly',
      startDate: formatDaysAgo(4),
      endDate: formatDaysFuture(3),
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
  ];

  const settings: Settings = {
    theme: 'light',
    weeklyTarget: 8,
    onboardingCompleted: true,
    userFullName: 'Alex Candidate',
    emailSignature: 'Alex Candidate\nLead Software & Automation Engineer\nlinkedin.com/in/alex-candidate-demo',
    followUpTemplates: DEFAULT_FOLLOW_UP_TEMPLATES,
  };

  return {
    jobs,
    resumes,
    interviews,
    activities,
    goals,
    settings,
  };
}
